# Generated by Django 4.0.4 on 2022-04-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
